version: '2'
services:
    disconf_mysql: 
        image: weixiaozheqingfu/disconf_mysql_5.7.27:20191018
        container_name: disconf_mysql
        restart: always
        networks: 
            default:    
                aliases: 
                    - mysqlhost
        environment: 
            MYSQL_ROOT_PASSWORD: root

    disconf_redis_01: 
        image: weixiaozheqingfu/disconf_redis_5.0.4:20191018
        container_name: disconf_redis_01
        restart: always
        depends_on:
            - disconf_mysql
        networks: 
            default: 
                aliases: 
                    - redishost001
        volumes: 
            - /root/data/redis01/data:/data
        command: redis-server /etc/redis/redis.conf

    disconf_redis_02:
        image: weixiaozheqingfu/disconf_redis_5.0.4:20191018
        container_name: disconf_redis_02
        restart: always
        depends_on:
            - disconf_redis_01
        networks: 
            default:    
                aliases: 
                    - redishost002
        volumes:
            - /root/data/redis02/data:/data
        command: redis-server /etc/redis/redis.conf

    disconf_zookeeper:
        image: zookeeper:3.3.6
        container_name: disconf_zookeeper
        restart: always
        depends_on:
            - disconf_redis_02
        networks: 
            default: 
                aliases: 
                    - zkhost
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zkhost:2888:3888
        ports: 
            - "2181:2181"

    #disconf_zookeeper_01:
    #    image: zookeeper:3.3.6
    #    restart: always
    #    container_name: disconf_zookeeper_01
    #    depends_on:
    #        - disconf_redis_02
    #    networks: 
    #        default: 
    #            aliases: 
    #                - zkhost001
    #    environment:
    #        ZOO_MY_ID: 1
    #        ZOO_SERVERS: server.1=zkhost001:2888:3888 server.2=zkhost002:2888:3888 server.3=zkhost003:2888:3888
    #disconf_zookeeper_02:
    #    image: zookeeper:3.3.6
    #    restart: always
    #    container_name: disconf_zookeeper_02
    #    depends_on:
    #        - disconf_zookeeper_01
    #    networks: 
    #        default: 
    #            aliases: 
    #                - zkhost002
    #    environment:
    #        ZOO_MY_ID: 2
    #        ZOO_SERVERS: server.1=zkhost001:2888:3888 server.2=zkhost002:2888:3888 server.3=zkhost003:2888:3888
    #disconf_zookeeper_03:
    #    image: zookeeper:3.3.6
    #    restart: always
    #    container_name: disconf_zookeeper_03
    #    depends_on:
    #        - disconf_zookeeper_02
    #    networks: 
    #        default: 
    #            aliases: 
    #                - zkhost003
    #   environment: 
    #       ZOO_MY_ID: 3
    #       ZOO_SERVERS: server.1=zkhost001:2888:3888 server.2=zkhost002:2888:3888 server.3=zkhost003:2888:3888

    disconf_tomcat: 
        image: weixiaozheqingfu/disconf_tomcat_8.5.46:20191018
        container_name: disconf_tomcat
        restart: always
        depends_on:
            - disconf_zookeeper
        networks: 
            default:        
                aliases:       
                    - tomcathost
    disconf_nginx: 
        image: weixiaozheqingfu/disconf_nginx_1.17.2:20191018
        container_name: disconf_nginx
        restart: always
        depends_on:
            - disconf_tomcat
        networks: 
            default:        
                aliases:       
                    - nginxhost
        ports: 
            - "80:80"

    disconf_java: 
        image: weixiaozheqingfu/stand_alone_demo:20191018
        container_name: disconf_java
        restart: always
        depends_on:
            - disconf_nginx
            - disconf_zookeeper
            - disconf_tomcat


        