version: '2'
services:
    elk: 
        image: elk:20191119
        container_name: elk
        restart: always
        networks: 
            default:    
                aliases: 
                    - elkhost
        ports: 
            - "15601:5601"
    elk-nginx: 
        image: weixiaozheqingfu/elk-nginx:20191119
        container_name: elk-nginx
        restart: always
        depends_on:
            - elk
        networks: 
            default:        
                aliases:       
                    - elk-nginx-host
        ports: 
            - "180:80"        
    elk-app-log4j2-jar: 
        image: weixiaozheqingfu/elk-app-log4j2-jar:20191119
        container_name: elk-app-log4j2-jar
        restart: always
        depends_on:
            - elk
        networks: 
            default:        
                aliases:       
                    - elk-app-log4j2-jar-host
        ports: 
            - "18080:8080"
    elk-app-mybatis-war: 
        image: weixiaozheqingfu/elk-app-mybatis-war:20191119
        container_name: elk-app-mybatis-war
        restart: always
        depends_on:
            - elk
        networks: 
            default:        
                aliases:       
                    - elk-app-mybatis-war-host
        ports: 
            - "18081:8080"                
    


        