version: '2'
services:
    disconf_mysql: 
        image: weixiaozheqingfu/docker_image_mysql_5.7.27:20191015
        restart: always
        container_name: disconf_mysql
        networks:
            mynet:              
                aliases:        
                    - mysqlhost
        environment:
            MYSQL_ROOT_PASSWORD: root
    disconf_redis_01:
        image: weixiaozheqingfu/docker_image_redis_5.0.4:20191015
        container_name: disconf_redis_01
        restart: always
        networks:
            mynet:              
                aliases:
                    - redishost001
        volumes:
            - /root/data/redis01/data:/data
        command: redis-server /etc/redis/redis.conf
    disconf_redis_02:
        image: weixiaozheqingfu/docker_image_redis_5.0.4:20191015
        container_name: disconf_redis_01
        restart: always
        networks:
            mynet:              
                aliases:
                    - redishost002
        volumes:
            - /root/data/redis02/data:/data
        command: redis-server /etc/redis/redis.conf        
    disconf_zookeeper:
        image: zookeeper:3.3.6
        restart: always
        container_name: disconf_zookeeper
        networks:
            mynet:              
                aliases:        
                    - zkhost001
        environment:
            ZOO_MY_ID: 1
            ZOO_SERVERS: server.1=zkhost001:2888:3888 server.2=zkhost002:2888:3888 server.3=zkhost003:2888:3888
    disconf_zookeeper:
        image: zookeeper:3.3.6
        restart: always
        container_name: disconf_zookeeper
        networks:
            mynet:              
                aliases:        
                    - zkhost002
        environment:
            ZOO_MY_ID: 2
            ZOO_SERVERS: server.1=zkhost001:2888:3888 server.2=zkhost002:2888:3888 server.3=zkhost003:2888:3888
    disconf_zookeeper:
        image: zookeeper:3.3.6
        restart: always
        container_name: disconf_zookeeper
        networks:
            mynet:              
                aliases:        
                    - zkhost003
        environment:
            ZOO_MY_ID: 3
            ZOO_SERVERS: server.1=zkhost001:2888:3888 server.2=zkhost002:2888:3888 server.3=zkhost003:2888:3888

      
    # TODO
    disconf_tomcat: 
      image: bolingcavalry/disconf_tomcat:0.0.1
      restart: always

    # TODO
    disconf_nginx: 
      image: bolingcavalry/disconf_nginx:0.0.1
      links: 
        - disconf_tomcat:tomcathost 
      ports: 
        - "80:80" 
      restart: always


networks:
    mynet: