version: '2'
services:
  rabbitmq:
    image: weixiaozheqingfu/rabbitmq-server:20191123
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      default: 
        aliases: 
          - rabbitmqhost
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=888888
  producer:
    image: weixiaozheqingfu/rabbitmq-producer:20191126
    container_name: producer
    hostname: producer
    depends_on:
        - rabbitmq
    ports:
        - "18080:8080"
    networks: 
      default: 
        aliases: 
          - producerhost
    environment:
     - mq.rabbit.address=rabbitmqhost:5672
     - mq.rabbit.username=admin
     - mq.rabbit.password=888888
     - mq.rabbit.exchange.name=producer.first.fanout.exchange
  consumer:
    image: weixiaozheqingfu/rabbitmq-consumer:20191126
    container_name: consumer
    hostname: consumer
    depends_on:
        - producer
    networks: 
      default: 
        aliases: 
          - consumerhost
    environment:
     - mq.rabbit.address=rabbitmqhost:5672
     - mq.rabbit.username=admin
     - mq.rabbit.password=888888
     - mq.rabbit.exchange.name=producer.first.fanout.exchange
     - mq.rabbit.queue.name=consumer1.first.fanout.queue
