version: '2'
services:
  rabbitmq1:
    image: weixiaozheqingfu/rabbitmq-server:20191123
    hostname: rabbitmq1
    ports:
      - "15672:15672"
    networks: 
      default: 
        aliases: 
          - rabbitmqhost1
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=888888
  rabbitmq2:
    image: weixiaozheqingfu/rabbitmq-server:20191123
    hostname: rabbitmq2
    ports:
      - "15673:15672"
    networks: 
      default: 
        aliases: 
          - rabbitmqhost2
    depends_on:
      - rabbitmq1
    environment:
        - CLUSTERED=true
        - CLUSTER_WITH=rabbitmq1
        - RAM_NODE=true
  rabbitmq3:
    image: weixiaozheqingfu/rabbitmq-server:20191123
    hostname: rabbitmq3
    ports:
      - "15675:15672"
    networks: 
      default: 
        aliases: 
          - rabbitmqhost3
    depends_on:
      - rabbitmq2
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq1
  #producer:
  #  image: bolingcavalry/rabbitmqproducer:0.0.2-SNAPSHOT
  #  hostname: producer
  #  depends_on:
  #    - rabbit3
  #  links:
  #    - rabbit1:rabbitmqhost
  #  ports:
  #    - "18080:8080"
  #  environment:
  #    - mq.rabbit.address=rabbitmqhost:5672
  #    - mq.rabbit.username=admin
  #    - mq.rabbit.password=888888
  #consumer1:
  #  image: bolingcavalry/rabbitmqconsumer:0.0.5-SNAPSHOT
  #  hostname: consumer1
  #  depends_on:
  #    - producer
  #  links:
  #    - rabbit2:rabbitmqhost
  #  environment:
  #   - mq.rabbit.address=rabbitmqhost:5672
  #   - mq.rabbit.username=admin
  #   - mq.rabbit.password=888888
  #   - mq.rabbit.queue.name=consumer1.queue
  #consumer2:
  #  image: bolingcavalry/rabbitmqconsumer:0.0.5-SNAPSHOT
  #  hostname: consumer2
  #  depends_on:
  #    - consumer1
  #  links:
  #    - rabbit3:rabbitmqhost
  #  environment:
  #    - mq.rabbit.address=rabbitmqhost:5672
  #    - mq.rabbit.username=admin
  #    - mq.rabbit.password=888888
  #    - mq.rabbit.queue.name=consumer2.queue
