version: '2'
services:
  rabbitmq1:
    image: weixiaozheqingfu/rabbitmq-server:20191123
    container_name: rabbitmq1
    hostname: rabbitmq1
    ports:
      - "5672:5672"
      - "15672:15672"
    networks: 
      default: 
        aliases: 
          - rabbitmq1host
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=888888
  rabbitmq2:
    image: weixiaozheqingfu/rabbitmq-server:20191123
    container_name: rabbitmq2
    hostname: rabbitmq2
    ports:
      - "5673:5672"
      - "15673:15672"
    networks: 
      default: 
        aliases: 
          - rabbitmq2host
    depends_on:
      - rabbitmq1
    environment:
        - CLUSTERED=true
        - CLUSTER_WITH=rabbitmq1
        - RAM_NODE=true
  rabbitmq3:
    image: weixiaozheqingfu/rabbitmq-server:20191123
    container_name: rabbitmq3
    hostname: rabbitmq3
    ports:
      - "5675:5672"
      - "15675:15672"
    networks: 
      default: 
        aliases: 
          - rabbitmq3host
    depends_on:
      - rabbitmq2
    environment:
      - CLUSTERED=true
      - CLUSTER_WITH=rabbitmq1
  producer:
    image: weixiaozheqingfu/rabbitmq-producer:20191126
    container_name: producer
    hostname: producer
    depends_on:
        - rabbitmq3
    ports:
        - "18080:8080"
    networks: 
      default: 
        aliases: 
          - producerhost
    environment:
     - mq.rabbit.address=rabbitmq1host:5672
     - mq.rabbit.username=admin
     - mq.rabbit.password=888888
     - mq.rabbit.exchange.name=producer.first.fanout.exchange
  consumer1:
    image: weixiaozheqingfu/rabbitmq-consumer:20191126
    container_name: consumer1
    hostname: consumer1
    depends_on:
        - producer
    networks: 
      default: 
        aliases: 
          - consumer1host
    environment:
     - mq.rabbit.address=rabbitmq2host:5672
     - mq.rabbit.username=admin
     - mq.rabbit.password=888888
     - mq.rabbit.exchange.name=producer.first.fanout.exchange
     - mq.rabbit.queue.name=consumer1.first.fanout.queue
  consumer2:
    image: weixiaozheqingfu/rabbitmq-consumer:20191126
    container_name: consumer2
    hostname: consumer2
    depends_on:
        - consumer1
    networks: 
      default: 
        aliases: 
          - consumer2host
    environment:
     - mq.rabbit.address=rabbitmq3host:5672
     - mq.rabbit.username=admin
     - mq.rabbit.password=888888
     - mq.rabbit.exchange.name=producer.first.fanout.exchange
     - mq.rabbit.queue.name=consumer2.first.fanout.queue
